export const assetActionTypes = Object.freeze({
  FETCH_ASSETS: "FETCH_ASSETS",
  FETCH_ASSETS_SUCCESS: "FETCH_ASSETS_SUCCESS",
  FETCH_ASSETS_ERROR: "FETCH_ASSETS_ERROR",
  FETCHAVAILABLE_ASSETS: "FETCHAVAILABLE_ASSETS",
  FETCHNON_INVASSETS: "FETCHNON_INVASSETS",
  FETCH_ASSET_BY_ID: "FETCH_ASSET_BY_ID",
  FETCHDECOMMISSION_ASSETS: "FETCHDECOMMISSION_ASSETS",
  ADD_ASSET: "ADD_ASSET",
  ADD_ASSET_SUCCESS: "ADD_ASSET_SUCCESS",
  UPDATE_ASSET: "UPDATE_ASSET",
  UPDATE_ASSET_SUCCESS: "UPDATE_ASSET_SUCCESS",
  DELETE_ASSET: "DELETE_ASSET",
  DELETE_ASSET_SUCCESS: "DELETE_ASSET_SUCCESS",
});

export const authActions = Object.freeze({
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
});
